### ISSUE TITLE
提前加载

### ISSUE THREAD

**Issue by huyongyong1992** [hoc2019/react-lazy-load#2]
现在默认是当滚动到该图片位置时（`$node.getBoundingClientRect().top <window. innerHeight`），加载该图片。但是可以通过设置一个参数来实现滚到距离其`xx px`时就加载（用户滑倒第二屏的时候不会感知到懒加载效果。） @ZhaoJianXXXXX

**Comment by ZhaoJianXXXXX** [comment]
厉害了勇哥 已经加了

**Comment by sl2782087** [comment]
> 现在默认是当滚动到该图片位置时（`$node.getBoundingClientRect().top <window. innerHeight`），加载该图片。但是可以通过设置一个参数来实现滚到距离其`xx px`时就加载（用户滑倒第二屏的时候不会感知到懒加载效果。） @ZhaoJianXXXXX

别提issue，提PR啊。
